### ISSUE TITLE
freeze after updating from 0.0.8 to 0.1.0

### ISSUE THREAD

**Issue by adrcotfas** [TheAndroidMaster/Attribouter#46]
When updating the library version and opening an Attribouter fragment, I get the following error:

`W/System.err: java.lang.ClassNotFoundException: about
W/System.err:     at me.jfenn.attribouter.fragments.AboutFragment.onCreateView(AboutFragment.java:65)
W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "about" on path: DexPathList[[zip file ...
W/System.err:     at me.jfenn.attribouter.fragments.AboutFragment.onCreateView(AboutFragment.java:65)
W/System.err:     at me.jfenn.attribouter.fragments.AboutFragment.onCreateView(AboutFragment.java:90)
W/System.err:     at me.jfenn.attribouter.fragments.AboutFragment.onCreateView(AboutFragment.java:90)
W/System.err:     at me.jfenn.attribouter.fragments.AboutFragment.onCreateView(AboutFragment.java:90)
W/System.err:     at me.jfenn.attribouter.fragments.AboutFragment.onCreateView(AboutFragment.java:90)
W/System.err:     at me.jfenn.attribouter.fragments.AboutFragment.onCreateView(AboutFragment.java:90)
W/System.err:     at me.jfenn.attribouter.fragments.AboutFragment.onCreateView(AboutFragment.java:90)
W/System.err:     at me.jfenn.attribouter.fragments.AboutFragment.onCreateView(AboutFragment.java:90)`

**Comment by TheAndroidMaster** [comment]
Could you provide a copy of your config file please?

**Comment by adrcotfas** [comment]
Sure.

```
<?xml version="1.0" encoding="utf-8"?>
<about>
    <appInfo repo="TheAndroidMaster/Attribouter"
        description="^">
        <link id="github" />
        <link
            hidden="true"
            id="website" />
    </appInfo>
    <translators>
        <translator
            name="Translator 1"
            avatar="@drawable/ic_tr"
            blog="https://example.com/"
            locales="zh" />
    </translators>
    <licenses
        title="Open Source Licences"
        showDefaults="false">
        <project repo="TheAndroidMaster/Attribouter" />
        <project repo="Gericop/Android-Support-Preference-V7-Fix" />
    </licenses>
</about>
```

**Comment by TheAndroidMaster** [comment]
Well first off, you'll want to follow the instructions in the [release description](https://github.com/TheAndroidMaster/Attribouter/releases/tag/v0.1.0). I'm not sure why it's complaining about the "about" tag though, as that shouldn't need to be changed. Meh, try that first and lmk what happens.

**Comment by divadsn** [comment]
Still happening, will post config shortly
