### ISSUE TITLE
Crash on interaction with contributor

### ISSUE THREAD

**Issue by TheAndroidMaster** [TheAndroidMaster/Attribouter#55]
Pretty sure this is just a case of an empty URL string being passed to the `UrlClickListener` class. Weird stack trace though.

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: me.jfenn.attriboutersample, PID: 20401
                  android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat= (has extras) }
                      at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1816)
                      at android.app.Instrumentation.execStartActivity(Instrumentation.java:1525)
                      at android.app.Activity.startActivityForResult(Activity.java:4317)
                      at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:767)
                      at android.app.Activity.startActivityForResult(Activity.java:4276)
                      at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:754)
                      at android.app.Activity.startActivity(Activity.java:4600)
                      at androidx.core.content.ContextCompat.startActivity(ContextCompat.java:248)
                      at androidx.browser.customtabs.CustomTabsIntent.launchUrl(CustomTabsIntent.java:263)
                      at me.jfenn.attribouter.utils.UrlClickListener.onClick(UrlClickListener.java:19)
                      at android.view.View.performClick(View.java:5623)
                      at android.view.View$PerformClick.run(View.java:22433)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6316)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
```

**Comment by TheAndroidMaster** [comment]
I was right. Added an empty check to the `LinkWedge` that was creating it & told the `ContributorWedge`s to ignore null listeners.
